### ISSUE TITLE
Unable to contact via email, prompt example

### ISSUE THREAD

**Issue by openapphub** [jaywcjlove/devtutor#3]
<img width="367" alt="image" src="https://github.com/user-attachments/assets/b3d10f25-50c3-4d98-a313-ae62ffa71eaa">
<img width="465" alt="image" src="https://github.com/user-attachments/assets/7656a130-c4bf-41b0-8be9-81dc47ae3f80">

**Comment by jaywcjlove** [comment]
@openapphub Got it! Thanks for the heads-up.
